### ISSUE TITLE
What is it? (Ubuntu 18.10)

### ISSUE THREAD

**Issue by vladislavyuzbekov** [DragonComputer/Dragonfire#110] opened 2019-03-06 16:58 UTC
vladislav@ubuntu:~$ dragonfire
Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PeakUtils' distribution was not found and is required by dragonfire

**Comment by lebedov** [comment] 2019-03-06 18:16
It appears that the latest Ubuntu package (1.0.2) doesn't several of the Python packages required by Dragonfire (e.g., peakutils, pyqtgraph, imutils).

**Comment by mertyildiran** [comment] 2019-03-07 06:55
I'm sorry for the inconvenience. The issue is fixed with fbea83fc884b07a92b5a0c05db4bbe67abf995c7

I have updated the `.deb` package in the [latest release](https://github.com/DragonComputer/Dragonfire/releases/tag/v1.0.2).

Please confirm the issue is fixed and feel free to report further issues if there are any. :blush:

**Comment by vladislavyuzbekov** [comment] 2019-03-07 16:58
> I'm sorry for the inconvenience. The issue is fixed with [fbea83f](https://github.com/DragonComputer/Dragonfire/commit/fbea83fc884b07a92b5a0c05db4bbe67abf995c7)
> 
> I have updated the `.deb` package in the [latest release](https://github.com/DragonComputer/Dragonfire/releases/tag/v1.0.2).
> 
> Please confirm the issue is fixed and feel free to report further issues if there are any. blush

vladislav@ubuntu:~$ dragonfire
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (nltk 3.3 (/usr/lib/python3/dist-packages), Requirement.parse('nltk==3.1'), {'dragonfire'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nltk==3.1' distribution was not found and is required by dragonfire

**Comment by mertyildiran** [comment] 2019-03-07 18:39
@vladislavyuzbekov fixed with 3731ac9c66aad78581be286ecc26ee560e22bcb3

I have updated the `.deb` package in the [latest release](https://github.com/DragonComputer/Dragonfire/releases/tag/v1.0.2).

Please try it one more time. :sweat_smile: 

By the way you can build your own Debian packages by following [the guide](https://github.com/DragonComputer/Dragonfire/blob/master/CONTRIBUTING.md#build-the-debian-package) to find solutions for installation problems. Hence you might want send pull requests that are fixing those issues and eventually contribute to this project directly. :blush:

**Comment by vladislavyuzbekov** [comment] 2019-03-08 05:06
> @vladislavyuzbekov fixed with [3731ac9](https://github.com/DragonComputer/Dragonfire/commit/3731ac9c66aad78581be286ecc26ee560e22bcb3)
> 
> I have updated the `.deb` package in the [latest release](https://github.com/DragonComputer/Dragonfire/releases/tag/v1.0.2).
> 
> Please try it one more time. sweat_smile
> 
> By the way you can build your own Debian packages by following [the guide](https://github.com/DragonComputer/Dragonfire/blob/master/CONTRIBUTING.md#build-the-debian-package) to find solutions for installation problems. Hence you might want send pull requests that are fixing those issues and eventually contribute to this project directly. blush

vladislav@ubuntu:~$ dragonfire
TensorFlow detected: v1.0.0

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /usr/share/dragonfire/deepconv/model-pretrainedv2/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /usr/share/dragonfire/deepconv/model-pretrainedv2/model.ckpt
________________________________________________________________________________

Dragonfire: GOOD MORNING SIR
________________________________________________________________________________

2019-03-08 08:05:20,954 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-03-08 08:05:20,954 INFO sqlalchemy.engine.base.Engine ()
2019-03-08 08:05:20,956 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-03-08 08:05:20,956 INFO sqlalchemy.engine.base.Engine ()
2019-03-08 08:05:20,957 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("users")
2019-03-08 08:05:20,957 INFO sqlalchemy.engine.base.Engine ()
2019-03-08 08:05:20,958 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("facts")
2019-03-08 08:05:20,958 INFO sqlalchemy.engine.base.Engine ()
2019-03-08 08:05:20,958 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("notifications")
2019-03-08 08:05:20,958 INFO sqlalchemy.engine.base.Engine ()
2019-03-08 08:05:20,959 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("notepad")
2019-03-08 08:05:20,959 INFO sqlalchemy.engine.base.Engine ()
Недопустимая инструкция (стек памяти сброшен на диск)

**Comment by lebedov** [comment] 2019-03-08 13:21
Installation of the latest deb file works for me now. Thanks!

**Comment by mertyildiran** [comment] 2019-03-08 20:32
Glad that this issue is solved. Thanks for the feedback. :blush:

**Closed by mertyildiran** 2019-03-08 20:32 UTC
