### ISSUE TITLE
Install instructions are lacking details

### ISSUE THREAD

**Issue by aggsol** [DragonComputer/Dragonfire#40] opened 2017-10-19 07:00 UTC
System: Ubuntu 16.04.2 ia64

I tried:
```
sudo dpkg -i dragonfire_0.9.6_amd64.deb && sudo apt-get -f install
```

but that just lists all missing dependencies and removes dragonfire. Nothing is installed. More detailed instructions are required. What are the dependencies? Why are they not installed first?

**Comment by mertyildiran** [comment] 2017-10-19 08:01
@aggsol `dpkg` is a program that unable to get package dependencies from Debian/Ubuntu's repositories. So with `sudo dpkg -i dragonfire_0.9.6_amd64.deb` you declare your intention to install Dragonfire and it gives you the list of missing dependencies.

Then with `-f` option of `apt-get` you fix broken packages:

```
-f, --fix-broken
           Fix; attempt to correct a system with broken dependencies in place. This option, when used with install/remove, can omit any packages to permit APT to deduce a likely
           solution. If packages are specified, these have to completely correct the problem. The option is sometimes necessary when running APT for the first time; APT itself does not
           allow broken package dependencies to exist on a system. It is possible that a system's dependency structure can be so corrupt as to require manual intervention (which
           usually means using dpkg --remove to eliminate some of the offending packages). Use of this option together with -m may produce an error in some situations. Configuration
           Item: APT::Get::Fix-Broken.
```

`sudo dpkg -i dragonfire_0.9.6_amd64.deb && sudo apt-get -f install` command works perfectly fine on my system (I just tested). I don't think there is a difference but you can try to run them separately.

These are [the dependencies](https://github.com/DragonComputer/Dragonfire/blob/master/debian/control#L11) of Dragonfire. You can try to install them by hand, as the last resort.

**Comment by aggsol** [comment] 2017-10-19 16:46
@mertyildiran I get the following output

```
$ sudo dpkg -i dragonfire_0.9.6_amd64.deb && sudo apt-get -f install
Selecting previously unselected package dragonfire.
(Reading database ... 310045 files and directories currently installed.)
Preparing to unpack dragonfire_0.9.6_amd64.deb ...
Unpacking dragonfire (0.9.6) ...
dpkg: dependency problems prevent configuration of dragonfire:
 dragonfire depends on flite; however:
  Package flite is not installed.
 dragonfire depends on python-xlib; however:
  Package python-xlib is not installed.
 dragonfire depends on portaudio19-dev; however:
  Package portaudio19-dev is not installed.
 dragonfire depends on flac; however:
  Package flac is not installed.
 dragonfire depends on python-egenix-mx-base-dev; however:
  Package python-egenix-mx-base-dev is not installed.
 dragonfire depends on python-nltk; however:
  Package python-nltk is not installed.
 dragonfire depends on python-pyaudio; however:
  Package python-pyaudio is not installed.
 dragonfire depends on python-wxgtk3.0; however:
  Package python-wxgtk3.0 is not installed.
 dragonfire depends on libgstreamer1.0-dev; however:
  Package libgstreamer1.0-dev is not installed.

dpkg: error processing package dragonfire (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 dragonfire
```

**Comment by mertyildiran** [comment] 2017-10-19 17:11
@aggsol look the problem is `&&` waits for a success but `sudo dpkg -i dragonfire_0.9.6_amd64.deb` returns an error, so it does not execute `sudo apt-get -f install`. You should run them one by one:

`sudo dpkg -i dragonfire_0.9.6_amd64.deb` [Enter]
`sudo apt-get -f install` [Enter]

`sudo dpkg -i dragonfire_0.9.6_amd64.deb && sudo apt-get -f install` does not work if you have missing dependencies.

**Comment by aggsol** [comment] 2017-10-19 17:46
okay that works. But still `pyowm' is now missing when starting.

```
$ dragonfire 
Traceback (most recent call last):
  File "/usr/share/python/dragonfire/bin/dragonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyowm' distribution was not found and is required by dragonfire

```

**Comment by mertyildiran** [comment] 2017-10-19 18:06
@aggsol please try to re-install it. I think you interrupted the installation and it didn't even install `pyowm` Python package.

**Comment by yuriw** [comment] 2017-10-20 20:58
Well it does not work for me either:

`sudo dpkg -i dragonfire_0.9.6_amd64.deb
(Reading database ... 391162 files and directories currently installed.)
Preparing to unpack dragonfire_0.9.6_amd64.deb ...
Unpacking dragonfire (0.9.6) over (0.9.6) ...
dpkg: dependency problems prevent configuration of dragonfire:
 dragonfire depends on flite; however:
  Package flite is not installed.
 dragonfire depends on python-xlib; however:
  Package python-xlib is not installed.
 dragonfire depends on portaudio19-dev; however:
  Package portaudio19-dev is not installed.
 dragonfire depends on flac; however:
  Package flac is not installed.
 dragonfire depends on python-egenix-mx-base-dev; however:
  Package python-egenix-mx-base-dev is not installed.
 dragonfire depends on python-nltk; however:
  Package python-nltk is not installed.
 dragonfire depends on python-pyaudio; however:
  Package python-pyaudio is not installed.
 dragonfire depends on libgstreamer1.0-dev; however:
  Package libgstreamer1.0-dev is not installed.

dpkg: error processing package dragonfire (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 dragonfire`

`sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libfreerdp-client1.1 libllvm3.8 libllvm3.8:i386 linux-headers-4.4.0-92 linux-headers-4.4.0-92-generic
  linux-headers-4.4.0-93 linux-headers-4.4.0-93-generic linux-image-4.4.0-92-generic linux-image-4.4.0-93-generic
  linux-image-extra-4.4.0-92-generic linux-image-extra-4.4.0-93-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  dragonfire
0 upgraded, 0 newly installed, 1 to remove and 111 not upgraded.
1 not fully installed or removed.
After this operation, 138 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 391161 files and directories currently installed.)
Removing dragonfire (0.9.6) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
 `

**Comment by mertyildiran** [comment] 2017-10-20 22:14
@yuriw please try to run `apt-get autoremove` to fix the situation and then try to install Dragonfire again.

**Comment by yuriw** [comment] 2017-10-20 22:38
@mertyildiran already tried and no love :-1:

**Comment by mertyildiran** [comment] 2017-10-20 23:38
@yuriw that's the standard procedure for any Debian(`.deb`) package.

Try to install the dependencies by hand with this command:
```
apt-get -y install python python-all-dev libglib2.0-dev libcairo2-dev libgtk2.0-dev python-wxgtk3.0 && \
apt-get -y install python2.7-minimal ${misc:Pre-Depends} && \
apt-get -y install ${python:Depends} ${misc:Depends} flite python-xlib portaudio19-dev python-all-dev flac libnotify-bin python-egenix-mx-base-dev python-lxml python-nltk python-pyaudio python-httplib2 python-pip python-wxgtk3.0 git libgstreamer1.0-dev gstreamer1.0-plugins-good gstreamer1.0-tools subversion libatlas-base-dev
```

and then try to install Debian package: `sudo dpkg -i dragonfire_0.9.6_amd64.deb`

As the last resort; you can try to run [install.sh](https://github.com/DragonComputer/Dragonfire/blob/master/install.sh) script after cloning the repository.

**Comment by yuriw** [comment] 2017-10-20 23:46
@mertyildiran this seems to be running, let it comply and then will try using it :)

**Comment by mertyildiran** [comment] 2017-10-20 23:51
@yuriw I'm glad to hear that it's worked. :+1: :blush:

**Comment by huayra** [comment] 2017-10-22 01:01
I can confirm that dragonfire works under Ubuntu 16.06 provided that you run the command above. It sort of solves #39 as least for me.

When starting my "Web Browser"shouldn't it start the default in the system (which in my case is Firefox)?

Otherwise funny :)

**Comment by mertyildiran** [comment] 2017-10-22 09:15
@huayra I'm glad to hear that. :+1: 

Dragonfire uses `sensible-browser` command to handle all web browser related tasks. Man page description:

```
DESCRIPTION
       sensible-editor,  sensible-pager  and  sensible-browser  make sensible decisions on which editor, pager, and web browser to call, respectively.  Programs in Debian can use these
       scripts as their default editor, pager, or web browser or emulate their behavior.
```

[How to configure sensible-browser to use firefox instead of chrome?](https://ubuntuforums.org/showthread.php?t=2212948)

**Comment by huayra** [comment] 2017-10-22 18:35
Thanks. That worked!

It is very promising I have to say. The biggest issue I have right  now is that it confuses itself because of its own sound feedback, so it goes into loops and becomes unusable as its own voice is recognized as part of the sentence/word I want it to process. Sometimes it somehow "hears" stuff I did not say. This happens even when there is silence around me (whole sentences, it might be delayed searching for something in i.e. Wikipedia).

**Comment by mertyildiran** [comment] 2017-10-22 20:51
@huayra currently, a better way is listening her with your headphones instead of speakers. The best way is using a headset with microphone included.

There will be some improvements on this matter in the future but we should avoid this discussion about **puzzling with her own voice** under this issue and move it to https://github.com/DragonComputer/Dragonfire/issues/26

**Comment by mertyildiran** [comment] 2017-10-28 02:31
All of the problems mentioned under this issue, are fixed in the [latest release](https://github.com/DragonComputer/Dragonfire/releases/tag/v0.9.7) of Dragonfire.

Feel free to open this issue again if you encounter with similar problems. :blush:

**Closed by mertyildiran** 2017-10-28 02:31 UTC
